### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luisrbferreira** [twentytwokhz/language-translator#17] opened 2023-06-30 15:40 UTC
Hi! I'm getting the following error when trying to translate texts:

"The operation is not allowed because the subscription has exceeded its free quota."

**Comment by valenzine** [comment] 2023-10-02 08:53
This is not a bug but expected behaviour: it's not unlimited. Get your own Azure API token and then set it up reading the [README.md](https://github.com/twentytwokhz/language-translator#readme) file

**Comment by gesantosur** [comment] 2024-02-14 21:35
When I try to translate any text, that text disappears and no longer appears

**Comment by twentytwokhz** [comment] 2024-02-26 18:26
@gesantosur that is now fixed with the latest **1.0.4** release

With regards to the initial text of the bug, @valenzine is correct:
You need to bring your own key in order to avoid exceeding the free quota.

My Azure quota for the free Translator service is `2M chars of any combination of standard translation`

**Closed as completed by twentytwokhz** 2024-02-26 18:26 UTC
Labels: bug
